# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7b4d967d108340427404a61a9f72285e4a233e6fd78abfd949f31e0d3ad379432915161d3c396ac8970846c3bb0280af5ac569b615ce10d301888a997d10dc6

test:
  secret_key_base: 08e3a2cc3ddbd789469f75aa51eaeb98cd4f33c501976d0cf46d9a9b207e53de17c91bd516b8d1b959d41c429b1c357e16a64ecc1fa4d5e0fc548633e993ae4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
